# MIT License

[tool.black]
line-length = 90

[tool.mypy]
plugins = []
namespace_packages = true
ignore_missing_imports = true
explicit_package_bases = true
check_untyped_defs = true

[tool.pylint]
ignore = []
load-plugins = ["pylint.extensions.typing"]

[tool.pylint.'MESSAGES CONTROL']
disable = [
    # Error:
    "not-an-iterable",
    "no-member",
    "not-callable",
    "no-value-for-parameter",
    "not-context-manager",
    "unsubscriptable-object",
    "no-name-in-module",
    "c-extension-no-member",
    "unspecified-encoding",
    "import-error",
    "unsupported-assignment-operation",

    # Warning:
    "broad-except",
    "fixme",
    "global-statement",
    "global-variable-not-assigned",
    "invalid-envvar-default",
    "invalid-overridden-method",
    "logging-fstring-interpolation",
    "pointless-statement",
    "protected-access",
    "redefined-builtin",
    "redefined-outer-name",
    "unused-wildcard-import",
    "wildcard-import",
    "unused-import",
    "exec-used",

    # Convention:
    "line-too-long",
    "invalid-name",
    "import-outside-toplevel",
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "unused-argument",

    # Refactor:
    "consider-using-with",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-ancestors",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-nested-blocks",
    "too-many-return-statements",
    "too-many-locals",
    "too-many-public-methods",
    "too-many-lines",
    "too-many-statements",
    "cyclic-import",
    "duplicate-code",
]

[tool.pytest.ini_options]
addopts = ["--strict-markers"]
python_files = ["tests.py", "test_*.py"]
markers = []
asyncio_mode = "auto"

[tool.coverage.run]
source = ["."]
omit = ["*/tests/*", "*/conftest.py"]
